/**
 * Route table. Pages are lazy-loaded from their feature folder; each feature agent owns its pages.
 * Paths are part of the shared contract — link to them with these constants.
 */
import { lazy } from 'react'

export const ROUTES = {
  today: '/',
  agenda: '/agenda',
  life: '/vida',
  lifeAdmin: '/vida/real',
  luna: '/vida/luna',
  inbox: '/inbox',
  tasks: '/tarefas',
  body: '/corpo',
  money: '/dinheiro',
  nutrition: '/nutricao',
  mealPrep: '/meal-prep',
  bodyEvolution: '/corpo/evolucao',
  goals: '/metas',
  work: '/trabalho',
  project: (id: string) => `/trabalho/projeto/${id}`,
  workInbox: '/trabalho/inbox',
  wins: '/trabalho/wins',
  creator: '/trabalho/creator',
  study: '/estudos',
  books: '/livros',
  book: (id: string) => `/livros/${id}`,
  trips: '/viagens',
  trip: (id: string) => `/viagens/${id}`,
  weeklyReview: '/revisao',
  weekPlanner: '/semana',
  monthlyReview: '/mes',
  search: '/busca',
  assistant: '/lumos',
  more: '/mais',
  settings: '/ajustes',
  customize: '/ajustes/personalizar',
  integrations: '/ajustes/integracoes',
  data: '/ajustes/dados',
  notifications: '/ajustes/notificacoes',
} as const

export const routeTable: { path: string; Component: React.LazyExoticComponent<React.ComponentType> }[] = [
  { path: '/', Component: lazy(() => import('@/features/today/TodayPage')) },
  { path: '/agenda', Component: lazy(() => import('@/features/agenda/AgendaPage')) },
  { path: '/vida', Component: lazy(() => import('@/features/life/LifePage')) },
  { path: '/vida/real', Component: lazy(() => import('@/features/life/LifeAdminPage')) },
  { path: '/vida/luna', Component: lazy(() => import('@/features/life/LunaPage')) },
  { path: '/inbox', Component: lazy(() => import('@/features/inbox/InboxPage')) },
  { path: '/tarefas', Component: lazy(() => import('@/features/tasks/TasksPage')) },
  { path: '/corpo', Component: lazy(() => import('@/features/body/BodyPage')) },
  { path: '/nutricao', Component: lazy(() => import('@/features/nutrition/NutritionPage')) },
  { path: '/meal-prep', Component: lazy(() => import('@/features/mealprep/MealPrepPage')) },
  { path: '/corpo/evolucao', Component: lazy(() => import('@/features/nutrition/EvolutionPage')) },
  { path: '/dinheiro', Component: lazy(() => import('@/features/finance/FinancePage')) },
  { path: '/metas', Component: lazy(() => import('@/features/goals/GoalsPage')) },
  { path: '/trabalho', Component: lazy(() => import('@/features/work/WorkPage')) },
  { path: '/trabalho/projeto/:id', Component: lazy(() => import('@/features/work/ProjectPage')) },
  { path: '/trabalho/inbox', Component: lazy(() => import('@/features/work/WorkInboxPage')) },
  { path: '/trabalho/wins', Component: lazy(() => import('@/features/work/WinsPage')) },
  { path: '/trabalho/creator', Component: lazy(() => import('@/features/creator/CreatorPage')) },
  { path: '/estudos', Component: lazy(() => import('@/features/learning/StudyPage')) },
  { path: '/livros', Component: lazy(() => import('@/features/learning/BooksPage')) },
  { path: '/livros/:id', Component: lazy(() => import('@/features/learning/BookPage')) },
  { path: '/viagens', Component: lazy(() => import('@/features/travel/TripsPage')) },
  { path: '/viagens/:id', Component: lazy(() => import('@/features/travel/TripPage')) },
  { path: '/semana', Component: lazy(() => import('@/features/planner/WeekPlannerPage')) },
  { path: '/revisao', Component: lazy(() => import('@/features/reviews/WeeklyReviewPage')) },
  { path: '/mes', Component: lazy(() => import('@/features/reviews/MonthlyReviewPage')) },
  { path: '/busca', Component: lazy(() => import('@/features/search/SearchPage')) },
  { path: '/lumos', Component: lazy(() => import('@/features/assistant/AssistantPage')) },
  { path: '/mais', Component: lazy(() => import('@/features/settings/MorePage')) },
  { path: '/ajustes', Component: lazy(() => import('@/features/settings/SettingsPage')) },
  { path: '/ajustes/personalizar', Component: lazy(() => import('@/features/settings/CustomizePage')) },
  { path: '/ajustes/integracoes', Component: lazy(() => import('@/features/integrations/IntegrationsPage')) },
  { path: '/ajustes/dados', Component: lazy(() => import('@/features/settings/DataPage')) },
  { path: '/ajustes/notificacoes', Component: lazy(() => import('@/features/settings/NotificationsPage')) },
]
